title: SaaS Generalist
logo: "images/logo.svg" # You can add own logo image.
description: SaaS Generalist is an attempt to build more generalists amongst the early stage SaaS employees
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://saasgeneralist.com/" # The base hostname & protocol for your site, e.g. http://example.com
title_image:

# Author Settings
author:
  name: Sanjeev NC
  bio: SaaS Generalist

# Contact links
twitter: https://twitter.com/yenceesanjeev # Add your Twitter handle
linkedin: https://www.linkedin.com/in/sanjeev-nc/
facebook:  # Add your Facebook handle
dribbble: # Add your Dribbble handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle
email: yenceesanjeev@gmail.com # Add your Email address

# Hero Section
hero: false # To enable the section hero, use the value true. To turn off use the value false.
hero-title: SaaS Generalist # Add your hero title
hero-subtitle:  # Add your hero subtitle
hero-image:  # Add background image in section hero

# Footer
footer-image:  # Add background image in footer

# Comment Section (Disqus)
disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

# Google Analytics
google-analytics: "UA-175604417-1" # Add your identifier. For example UA-99631805-1.

# Newsletter
mailchimp: "saasgeneralist.us10.list-manage.com/subscribe/post?u=4cbeb6f3cc30326f9e95ec3d7&amp;id=4a91b36376" # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 7
paginate_path: "/page/:num"

collection:
  dailys:
    output: true

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed
